name: Build Installers

on:
  push:
    tags:
      - 'v*' # Trigger on version tags
  workflow_dispatch: # Allow manual trigger

jobs:
  build-windows:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'
          
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install pyinstaller pillow
          
      - name: Build Windows executable
        run: |
          pyinstaller --name "LabSync" --windowed --onefile --add-data "src/gui/resources;gui/resources" src/main.py
          echo "Contents of dist after PyInstaller:"
          dir dist /s /b
          
      - name: Create Windows Installer
        run: |
          choco install innosetup -y
          echo "Running Inno Setup Compiler..."
          iscc "installer/windows/installer.iss"
          echo "Contents of dist after Inno Setup:"
          dir dist /s /b
          if not exist "dist\LabSync-Setup.exe" (
            echo "Error: Installer dist\LabSync-Setup.exe not found!"
            exit 1
          )
          
      - name: Upload Windows Artifact
        uses: actions/upload-artifact@v4
        with:
          name: windows-installer
          path: dist/LabSync-Setup.exe

  build-macos:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4 # Updated to v4 for consistency
      
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'
          
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install pyinstaller
          
      - name: Create icns file
        run: |
          mkdir icon.iconset
          sips -s format png src/gui/resources/icon.png --out icon.iconset/icon_512x512.png
          # Add other required sizes for a complete .icns set if needed
          sips -s format png src/gui/resources/icon.png -z 256 256 --out icon.iconset/icon_256x256.png
          sips -s format png src/gui/resources/icon.png -z 128 128 --out icon.iconset/icon_128x128.png
          iconutil -c icns icon.iconset -o LabSync.icns # Output directly as LabSync.icns
          echo "Generated LabSync.icns"
          ls -l LabSync.icns
          
      - name: Build macOS app
        run: |
          pyinstaller --name "LabSync" --windowed --onefile --add-data "src/gui/resources:gui/resources" --icon "LabSync.icns" src/main.py
          echo "Contents of dist after PyInstaller (macOS):"
          ls -R dist
          
      - name: Create DMG
        run: |
          # Ensure the .app bundle exists before creating DMG
          if [ ! -d "dist/LabSync.app" ]; then
            echo "Error: dist/LabSync.app not found!"
            exit 1
          fi
          hdiutil create -srcfolder "dist/LabSync.app" -volname "LabSync" -fs HFS+ -format UDZO -size 100m "dist/LabSync.dmg"
          echo "Contents of dist after DMG creation:"
          ls -R dist
          
      - name: Upload macOS Artifact
        uses: actions/upload-artifact@v4
        with:
          name: macos-installer
          path: dist/LabSync.dmg

  create-release:
    needs: [build-windows, build-macos]
    runs-on: ubuntu-latest
    if: startsWith(github.ref, 'refs/tags/')
    
    steps:
      - name: Download all artifacts
        uses: actions/download-artifact@v4
        # No need to specify name, it downloads all artifacts from the run by default
        # to separate directories based on artifact name.
        
      - name: List downloaded artifacts
        run: ls -R ./
        
      - name: Create Release
        uses: softprops/action-gh-release@v2
        with:
          files: |
            windows-installer/LabSync-Setup.exe
            macos-installer/LabSync.dmg
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}